# Generated by Django 3.1.3 on 2020-11-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geauth', '0004_user_salarie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salarie',
        ),
    ]
