# Generated by Django 3.1.3 on 2020-11-05 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0049_remove_salarie_user'),
        ('geauth', '0006_user_salarie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salarie',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='activite.salarie', verbose_name='Salarié'),
        ),
    ]
