# Generated by Django 3.1.3 on 2020-11-05 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0049_remove_salarie_user'),
        ('geauth', '0007_auto_20201105_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='salarie',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salarie', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='activite.salarie', verbose_name='Salarié')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
