# Generated by Django 5.1.1 on 2024-09-20 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geauth', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_laposte_manager',
            field=models.BooleanField(default=False, verbose_name='Est manager La Poste'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='la_poste_manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declare_pour', to=settings.AUTH_USER_MODEL, verbose_name='Nom du manager La Poste'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
