# Generated by Django 5.2 on 2025-05-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geauth', '0011_userprofile_is_laposte_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_laposte_manager',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='la_poste_manager',
        ),
    ]
