# Generated by Django 3.1.6 on 2021-02-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activite', '0053_auto_20210226_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendrierSalarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendrier_salarie_list', to='activite.salarie')),
            ],
        ),
        migrations.CreateModel(
            name='CalendrierSalariePeriode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True, verbose_name='Nom de la période')),
                ('ordre', models.IntegerField(verbose_name='ordre dans le jour')),
            ],
        ),
        migrations.CreateModel(
            name='CalendrierSalarieMiseADisposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(blank=True, default='', max_length=200, verbose_name='Notes')),
                ('num_jour', models.IntegerField(default=0, verbose_name='Jour')),
                ('calendrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mise_a_disposition_list', to='salarie.calendriersalarie')),
                ('periode', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='salarie.calendriersalarieperiode')),
            ],
        ),
    ]
