# Generated by Django 3.1.6 on 2021-02-26 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salarie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendriersalarie',
            options={'ordering': ['salarie__nom']},
        ),
        migrations.AlterModelOptions(
            name='calendriersalariemiseadisposition',
            options={'ordering': ['num_jour', 'periode__ordre']},
        ),
        migrations.AlterModelOptions(
            name='calendriersalarieperiode',
            options={'ordering': ['nom', 'ordre']},
        ),
    ]
