# Generated by Django 3.1.6 on 2021-03-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarie', '0004_auto_20210303_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendriersalarieperiode',
            options={'ordering': ['ordre', 'nom']},
        ),
        migrations.RemoveField(
            model_name='calendriersalarieperiode',
            name='calendrier',
        ),
        migrations.RemoveField(
            model_name='calendriersalarieperiode',
            name='num_jour',
        ),
        migrations.AddField(
            model_name='calendriersalariemiseadisposition',
            name='calendrier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mise_a_disposition_list', to='salarie.calendriersalarie'),
        ),
        migrations.AddField(
            model_name='calendriersalariemiseadisposition',
            name='num_jour',
            field=models.IntegerField(default=0, verbose_name='Jour'),
        ),
    ]
