# Generated by Django 3.1.6 on 2021-03-03 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0053_auto_20210226_0934'),
        ('salarie', '0005_auto_20210303_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendriersalariemiseadisposition',
            name='mad',
        ),
        migrations.AddField(
            model_name='calendriersalariemiseadisposition',
            name='adherent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activite.adherent'),
        ),
    ]
