# Generated by Django 3.1.6 on 2021-03-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0053_auto_20210226_0934'),
        ('salarie', '0006_auto_20210303_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendriersalariemiseadisposition',
            name='adherent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activite.adherent'),
        ),
    ]
