# Generated by Django 3.1.6 on 2021-03-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarie', '0007_auto_20210303_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendrierSalarieRecurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True, verbose_name='Nom de la période')),
                ('ordre', models.IntegerField(verbose_name='ordre dans le jour')),
            ],
            options={
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterField(
            model_name='calendriersalariemiseadisposition',
            name='periode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='salarie.calendriersalarieperiode'),
        ),
        migrations.AddField(
            model_name='calendriersalariemiseadisposition',
            name='recurence',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='salarie.calendriersalarierecurence'),
        ),
    ]
