# Generated by Django 3.1.6 on 2021-03-12 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salarie', '0009_auto_20210311_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendriersalariemiseadisposition',
            name='periode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salarie.calendriersalarieperiode'),
        ),
    ]
