# Generated by Django 3.1.3 on 2021-01-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoisStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(db_index=True)),
                ('annee', models.IntegerField(db_index=True)),
                ('ca_total', models.FloatField(db_index=True, default=0)),
                ('ca_progressis', models.FloatField(db_index=True, default=0)),
                ('heures_total', models.FloatField(db_index=True, default=0)),
                ('heures_progressis', models.FloatField(db_index=True, default=0)),
            ],
        ),
    ]
