# Generated by Django 3.0.7 on 2020-06-26 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_erp', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Code ERP')),
                ('raison_sociale', models.CharField(max_length=50, verbose_name='Code ERP')),
            ],
        ),
        migrations.CreateModel(
            name='Affaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_erp', models.CharField(max_length=18, verbose_name='Code ERP')),
                ('libelle', models.CharField(max_length=70, verbose_name='Libelle')),
                ('termine', models.BooleanField(default=False)),
                ('coef_vente_soumis', models.FloatField(verbose_name='Coef de vente soumis')),
                ('coef_vente_non_soumis', models.FloatField(verbose_name='Coef de vente non soumis')),
                ('heures_mensuelles', models.FloatField(verbose_name='Heures mensuelles')),
                ('heures_quotidiennes', models.FloatField(verbose_name='Heures quotidiennes')),
                ('adherent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affaire_list', to='activite.Adherent')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_erp', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Code ERP')),
                ('libelle', models.CharField(max_length=70, verbose_name='Libelle')),
            ],
        ),
        migrations.CreateModel(
            name='PosteAffaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_erp', models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Code ERP')),
                ('libelle', models.CharField(max_length=70, verbose_name='Libelle')),
            ],
        ),
        migrations.CreateModel(
            name='RubriquePaie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_erp', models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Code ERP')),
                ('libelle', models.CharField(max_length=70, verbose_name='Libelle')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAdherent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_erp', models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Code ERP')),
                ('libelle', models.CharField(max_length=70, verbose_name='Libelle')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAffaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_erp', models.CharField(blank=True, default=None, max_length=70, null=True, verbose_name='Code ERP')),
                ('libelle', models.CharField(max_length=70, verbose_name='Libelle')),
            ],
        ),
        migrations.CreateModel(
            name='TarifGe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=17, verbose_name='Poste')),
                ('tarif', models.FloatField(default=0, verbose_name='Tarif')),
                ('exportable', models.BooleanField(default=True, verbose_name='Exportable ?')),
                ('element_reference', models.CharField(max_length=17, verbose_name='Elt Nationnal de Référence')),
                ('coef', models.FloatField(default=0, verbose_name='Coefficient')),
                ('mode_calcul', models.IntegerField(verbose_name='Mode de Calcul')),
                ('coef_paie', models.FloatField(verbose_name='Coefficient de paie')),
                ('article_a_saisir', models.BooleanField(default=False, verbose_name='Article a saisir ?')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif_ge_list', to='activite.Affaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarif_ge_list', to='activite.Article')),
                ('article2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activite.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_erp', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Code ERP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaisieActivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(verbose_name='Quantité')),
                ('origine', models.CharField(max_length=17, verbose_name='Origine')),
                ('prix_revient', models.FloatField(verbose_name='Prix de Revient')),
                ('prix_vente', models.FloatField(verbose_name='Prix de Vente')),
                ('exporte', models.IntegerField(verbose_name='Exporte')),
                ('type_ligne', models.CharField(max_length=11, verbose_name='type_ligne')),
                ('created', models.DateTimeField(verbose_name='CreationH Creation')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisie_activite_list', to='activite.Affaire')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisie_activite_list', to='activite.Article')),
            ],
        ),
        migrations.CreateModel(
            name='DetailCreditTemps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_travaillees', models.FloatField(verbose_name='Heures Travaillées')),
                ('heures_mensuelles', models.FloatField(verbose_name='heures mensuelles')),
                ('saisiecomplete', models.BooleanField(verbose_name='Saise Comlète ?')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_credit_temps_list', to='activite.Affaire')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTemps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(verbose_name='Mois')),
                ('année', models.IntegerField(verbose_name='Année')),
                ('heures_travaillees', models.FloatField(verbose_name='Heures Travaillées')),
                ('heures_theoriques', models.FloatField(verbose_name='heures Théoriques')),
                ('id_detail', models.IntegerField(verbose_name='')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_temps', to='activite.Salarie')),
            ],
        ),
        migrations.AddField(
            model_name='affaire',
            name='salarie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affaire_list', to='activite.Salarie'),
        ),
        migrations.AddField(
            model_name='affaire',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affaire_list', to='activite.ServiceAdherent'),
        ),
        migrations.AddField(
            model_name='affaire',
            name='type_affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affaire_list', to='activite.TypeAffaire'),
        ),
    ]
