# Generated by Django 3.0.7 on 2020-07-01 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activite', '0002_rubriquepaie_abrege'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='nom',
            field=models.CharField(default='', max_length=200, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='prenom',
            field=models.CharField(default='', max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
