# Generated by Django 3.0.7 on 2020-07-01 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0003_auto_20200701_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rubrique_paie_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activite.RubriquePaie'),
        ),
        migrations.AddField(
            model_name='article',
            name='type_article',
            field=models.CharField(default='', max_length=70, verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='prenom',
            field=models.CharField(default='', max_length=200, verbose_name='Prenom'),
        ),
    ]
