# Generated by Django 3.0.7 on 2020-07-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0004_auto_20200701_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='rubrique_paie_code',
            new_name='rubrique_paie',
        ),
    ]
