# Generated by Django 3.0.7 on 2020-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0005_auto_20200701_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code_erp',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Code ERP'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type_article',
            field=models.CharField(default='', max_length=70, verbose_name='Type'),
        ),
    ]
