# Generated by Django 3.0.7 on 2020-07-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0006_auto_20200701_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaire',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='affaire',
            name='service',
        ),
        migrations.RemoveField(
            model_name='affaire',
            name='type_affaire',
        ),
        migrations.AlterField(
            model_name='affaire',
            name='coef_vente_non_soumis',
            field=models.FloatField(default=0, verbose_name='Coef de vente non soumis'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='coef_vente_soumis',
            field=models.FloatField(default=0, verbose_name='Coef de vente soumis'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='heures_mensuelles',
            field=models.FloatField(default=0, verbose_name='Heures mensuelles'),
        ),
        migrations.AlterField(
            model_name='affaire',
            name='heures_quotidiennes',
            field=models.FloatField(default=0, verbose_name='Heures quotidiennes'),
        ),
    ]
