# Generated by Django 3.0.7 on 2020-07-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0007_auto_20200701_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifge',
            name='code_erp',
            field=models.IntegerField(default=0),
        ),
    ]
