# Generated by Django 3.0.7 on 2020-07-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0009_auto_20200701_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifge',
            name='coef_paie',
            field=models.FloatField(null=True, verbose_name='Coefficient de paie'),
        ),
    ]
