# Generated by Django 3.0.7 on 2020-07-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0010_auto_20200701_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifge',
            name='coef_paie',
            field=models.FloatField(default=0, verbose_name='Coefficient de paie'),
        ),
    ]
