# Generated by Django 3.0.7 on 2020-07-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0011_auto_20200701_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifge',
            name='affaire',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarif_ge_list', to='activite.Affaire'),
        ),
    ]
