# Generated by Django 3.0.7 on 2020-07-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0012_auto_20200701_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifge',
            name='salarie',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activite.Salarie'),
        ),
    ]
