# Generated by Django 3.0.7 on 2020-07-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0013_tarifge_salarie'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='date_entree',
            field=models.DateField(default=None, null=True, verbose_name="Date d'entrée"),
        ),
        migrations.AddField(
            model_name='salarie',
            name='date_sortie',
            field=models.DateField(default=None, null=True, verbose_name='Date de sortie'),
        ),
        migrations.AlterField(
            model_name='saisieactivite',
            name='created',
            field=models.DateTimeField(verbose_name='Creation'),
        ),
    ]
