# Generated by Django 3.0.7 on 2020-07-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0014_auto_20200701_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarie',
            name='date_entree',
            field=models.DateField(blank=True, default=None, null=True, verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='salarie',
            name='date_sortie',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date de sortie'),
        ),
    ]
