# Generated by Django 3.0.7 on 2020-07-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0015_auto_20200701_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affaire',
            old_name='termine',
            new_name='cloturee',
        ),
    ]
