# Generated by Django 3.0.7 on 2020-07-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0017_auto_20200702_1526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PosteAffaire',
            new_name='Poste',
        ),
        migrations.RenameModel(
            old_name='ServiceAdherent',
            new_name='Service',
        ),
        migrations.AddField(
            model_name='affaire',
            name='Poste',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affaire_list', to='activite.Poste'),
        ),
        migrations.AddField(
            model_name='affaire',
            name='service',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affaire_list', to='activite.Service'),
        ),
    ]
