# Generated by Django 3.0.7 on 2020-07-02 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0018_auto_20200702_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affaire',
            old_name='Poste',
            new_name='poste',
        ),
    ]
