# Generated by Django 3.0.7 on 2020-07-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0019_auto_20200702_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifge',
            name='salarie',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarif_ge_list', to='activite.Salarie'),
        ),
    ]
