# Generated by Django 3.0.7 on 2020-07-08 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0020_auto_20200703_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiseADisposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_erp', models.CharField(max_length=18, verbose_name='Code ERP')),
                ('cloturee', models.BooleanField(default=False, verbose_name='Mise à disposition cloturée ?')),
                ('duree_travail_mensuel', models.FloatField(default=0, verbose_name='Temps de travail mensuel')),
                ('duree_travail_quotidien', models.FloatField(default=0, verbose_name='Temps de travail quotidien')),
                ('coef_vente_soumis', models.FloatField(default=0, verbose_name='Coef de vente soumis')),
                ('coef_vente_non_soumis', models.FloatField(default=0, verbose_name='Coef de vente non soumis')),
                ('adherent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mise_a_disposition_list', to='activite.Adherent')),
                ('poste', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mise_a_disposition_list', to='activite.Poste')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mise_a_disposition_list', to='activite.Salarie')),
                ('service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mise_a_disposition_list', to='activite.Service')),
            ],
        ),
        migrations.RemoveField(
            model_name='affaire',
            name='adherent',
        ),
        migrations.RemoveField(
            model_name='affaire',
            name='poste',
        ),
        migrations.RemoveField(
            model_name='affaire',
            name='salarie',
        ),
        migrations.RemoveField(
            model_name='affaire',
            name='service',
        ),
        migrations.DeleteModel(
            name='TypeAffaire',
        ),
        migrations.RemoveField(
            model_name='detailcredittemps',
            name='affaire',
        ),
        migrations.RemoveField(
            model_name='saisieactivite',
            name='affaire',
        ),
        migrations.RemoveField(
            model_name='tarifge',
            name='affaire',
        ),
        migrations.DeleteModel(
            name='Affaire',
        ),
        migrations.AddField(
            model_name='detailcredittemps',
            name='mise_a_disposition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='detail_credit_temps_list', to='activite.MiseADisposition'),
        ),
        migrations.AddField(
            model_name='saisieactivite',
            name='mise_a_disposition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saisie_activite_list', to='activite.MiseADisposition'),
        ),
        migrations.AddField(
            model_name='tarifge',
            name='mise_a_disposition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarif_ge_list', to='activite.MiseADisposition'),
        ),
    ]
