# Generated by Django 3.0.7 on 2020-07-08 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0021_auto_20200708_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifge',
            name='element_reference',
            field=models.CharField(blank=True, max_length=17, verbose_name='Elt Nationnal de Référence'),
        ),
        migrations.AlterField(
            model_name='tarifge',
            name='mise_a_disposition',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarif_ge_list', to='activite.MiseADisposition'),
        ),
        migrations.AlterField(
            model_name='tarifge',
            name='poste',
            field=models.CharField(blank=True, max_length=17, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='tarifge',
            name='salarie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarif_ge_list', to='activite.Salarie'),
        ),
    ]
