# Generated by Django 3.0.7 on 2020-07-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0022_auto_20200708_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaisiesActivite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_realisation', models.DateField(verbose_name='Date')),
                ('quantite', models.FloatField(verbose_name='Quantité')),
                ('created', models.DateTimeField(verbose_name='Creation')),
                ('updated', models.DateTimeField(verbose_name='Modification')),
                ('tarif', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='saisie_activite_list', to='activite.TarifGe')),
            ],
        ),
        migrations.DeleteModel(
            name='SaisieActivite',
        ),
    ]
