# Generated by Django 3.0.7 on 2020-07-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0023_auto_20200708_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaisiesActivite',
            new_name='SaisieActivite',
        ),
    ]
