# Generated by Django 3.0.7 on 2020-07-15 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0024_auto_20200708_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilleArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_erp', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Code ERP')),
                ('libelle', models.CharField(max_length=70, verbose_name='Libelle')),
                ('forfaitaire', models.BooleanField(default=False, verbose_name='Forfaitaire')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='famille',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_list', to='activite.FamilleArticle'),
        ),
    ]
