# Generated by Django 3.0.7 on 2020-07-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0025_auto_20200715_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifge',
            name='salarie',
        ),
    ]
