# Generated by Django 3.0.7 on 2020-07-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0028_tarifge_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ordre',
            field=models.IntegerField(db_index=True, default=0, null=True, verbose_name='Ordre'),
        ),
    ]
