# Generated by Django 3.0.7 on 2020-07-31 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0031_auto_20200731_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infossupmoismad',
            old_name='saisiecomplete',
            new_name='saisie_complete',
        ),
        migrations.AlterField(
            model_name='infossupmoismad',
            name='mise_a_disposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos_sup_list', to='activite.MiseADisposition'),
        ),
    ]
