# Generated by Django 3.0.7 on 2020-07-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0032_auto_20200731_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infossupmoismad',
            old_name='heures_mensuelles',
            new_name='heures_theoriques',
        ),
        migrations.RemoveField(
            model_name='infossupmoissalarie',
            name='id_detail',
        ),
        migrations.AddField(
            model_name='infossupmoismad',
            name='annee',
            field=models.IntegerField(default=0, verbose_name='Année'),
        ),
        migrations.AddField(
            model_name='infossupmoismad',
            name='mois',
            field=models.IntegerField(default=0, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='infossupmoismad',
            name='saisie_complete',
            field=models.BooleanField(default=None, null=True, verbose_name='Saise Comlète ?'),
        ),
    ]
