# Generated by Django 3.0.7 on 2020-10-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0034_auto_20201008_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='charges_soumises',
            field=models.BooleanField(default=True, verbose_name='Charges soumises ?'),
        ),
    ]
