# Generated by Django 3.0.7 on 2020-10-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0035_article_charges_soumises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='charges_soumises',
            field=models.BooleanField(default=True, null=True, verbose_name='Charges soumises ?'),
        ),
    ]
