# Generated by Django 3.0.7 on 2020-10-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0036_auto_20201008_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='facturation_uniquement',
            field=models.BooleanField(default=False, null=True, verbose_name='Facturation uniquement'),
        ),
    ]
