# Generated by Django 3.1.2 on 2020-10-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0038_remove_infossupmoissalarie_heures_travaillees'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarie',
            name='memo',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Mémo'),
        ),
        migrations.AlterField(
            model_name='infossupmoismad',
            name='annee',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='infossupmoismad',
            name='mois',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='infossupmoismad',
            name='saisie_complete',
            field=models.BooleanField(db_index=True, default=None, null=True, verbose_name='Saise Comlète ?'),
        ),
        migrations.AlterField(
            model_name='infossupmoissalarie',
            name='annee',
            field=models.IntegerField(db_index=True, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='infossupmoissalarie',
            name='heures_theoriques',
            field=models.FloatField(db_index=True, verbose_name='heures Théoriques'),
        ),
        migrations.AlterField(
            model_name='infossupmoissalarie',
            name='mois',
            field=models.IntegerField(db_index=True, verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='saisieactivite',
            name='created',
            field=models.DateTimeField(db_index=True, verbose_name='Creation'),
        ),
        migrations.AlterField(
            model_name='saisieactivite',
            name='date_realisation',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='saisieactivite',
            name='updated',
            field=models.DateTimeField(db_index=True, verbose_name='Modification'),
        ),
        migrations.AlterField(
            model_name='saisieactivite',
            name='uploaded',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Envoyée'),
        ),
        migrations.AlterField(
            model_name='tarifge',
            name='exportable',
            field=models.BooleanField(db_index=True, default=False, null=True, verbose_name='Exportable ?'),
        ),
        migrations.AlterField(
            model_name='tarifge',
            name='poste',
            field=models.CharField(blank=True, db_index=True, max_length=17, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='tarifge',
            name='tarif',
            field=models.FloatField(db_index=True, default=0, verbose_name='Tarif'),
        ),
    ]
