# Generated by Django 3.1.2 on 2020-10-27 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0039_auto_20201027_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifge',
            name='article2',
        ),
        migrations.AddField(
            model_name='tarifge',
            name='tarif_fils',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='activite.tarifge'),
        ),
        migrations.AlterField(
            model_name='tarifge',
            name='coef',
            field=models.FloatField(default=0, verbose_name='Coefficient appliqué au fils'),
        ),
    ]
