# Generated by Django 3.1.2 on 2020-10-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0040_auto_20201027_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifge',
            old_name='tarif_fils',
            new_name='tarif_pere',
        ),
        migrations.AlterField(
            model_name='tarifge',
            name='coef',
            field=models.FloatField(default=0, verbose_name='Coefficient appliqué au père'),
        ),
    ]
