# Generated by Django 3.1.2 on 2020-10-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0042_auto_20201028_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='infossupmoissalarie',
            name='difference_heures',
            field=models.FloatField(db_index=True, default=0, verbose_name='Différence théorique - réalisé'),
        ),
    ]
