# Generated by Django 3.1.2 on 2020-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0043_infossupmoissalarie_difference_heures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infossupmoissalarie',
            name='difference_heures',
            field=models.FloatField(db_index=True, default=0, verbose_name='Différence théorique - travaillé'),
        ),
    ]
