# Generated by Django 3.1.2 on 2020-10-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0044_auto_20201029_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='infossupmoissalarie',
            name='paie_envoyee',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Paie Envoyée ?'),
        ),
    ]
