# Generated by Django 3.1.3 on 2020-11-05 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0048_salarie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarie',
            name='user',
        ),
    ]
