# Generated by Django 3.1.3 on 2020-12-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0050_auto_20201105_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='infossupmoismad',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='Memo'),
        ),
    ]
