# Generated by Django 3.1.3 on 2020-12-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0051_infossupmoismad_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='infossupmoissalarie',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='Memo'),
        ),
    ]
