# Generated by Django 3.1.6 on 2021-02-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0052_infossupmoissalarie_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infossupmoismad',
            name='saisie_complete',
            field=models.BooleanField(db_index=True, default=None, null=True, verbose_name='Saise Complète ?'),
        ),
    ]
