# Generated by Django 4.0.3 on 2022-03-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0054_auto_20210526_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='infossupmoissalarie',
            name='difference_heures_mois_precedent',
            field=models.FloatField(db_index=True, default=0, verbose_name='Différence mois N-1'),
        ),
    ]
