# Generated by Django 4.0.3 on 2022-03-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0055_infossupmoissalarie_difference_heures_mois_precedent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infossupmoissalarie',
            old_name='difference_heures_mois_precedent',
            new_name='compteur_mois_precedent',
        ),
        migrations.AddField(
            model_name='infossupmoissalarie',
            name='ajustement_mois',
            field=models.FloatField(db_index=True, default=0, verbose_name='Ajustement du mois'),
        ),
        migrations.AddField(
            model_name='infossupmoissalarie',
            name='compteur_mois',
            field=models.FloatField(db_index=True, default=0, verbose_name='Compteur du mois'),
        ),
    ]
