# Generated by Django 4.0.3 on 2022-04-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0056_rename_difference_heures_mois_precedent_infossupmoissalarie_compteur_mois_precedent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infossupmoissalarie',
            name='heures_travaillees',
            field=models.FloatField(db_index=True, default=0, verbose_name='Heures Travaillées'),
        ),
    ]
