# Generated by Django 4.1 on 2022-09-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='Clef')),
                ('str_val', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valeur Chaine')),
                ('int_val', models.IntegerField(verbose_name='Valeur Entière')),
            ],
        ),
    ]
