# Generated by Django 4.1 on 2022-09-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='int_val',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valeur Entière'),
        ),
    ]
