# Generated by Django 4.1 on 2022-09-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_config_int_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='description'),
        ),
    ]
