# Generated by Django 3.1.3 on 2020-11-05 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activite', '0046_auto_20201105_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveSalarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(db_index=True, verbose_name='Mois')),
                ('annee', models.IntegerField(db_index=True, verbose_name='Année')),
                ('saisie_complete', models.BooleanField(db_index=True, verbose_name='Saisie Complète ?')),
                ('saisie_complete_date', models.DateTimeField(verbose_name='Date de Saisie Complete')),
                ('commentaire', models.TextField(verbose_name='Commentaires')),
                ('created', models.DateTimeField(verbose_name='Date de création')),
                ('updated', models.DateTimeField(verbose_name='Date de modification')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releve_heures_list', to=settings.AUTH_USER_MODEL, verbose_name='Salarié')),
            ],
        ),
        migrations.CreateModel(
            name='SaisieSalarie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('heures', models.FloatField(db_index=True, verbose_name='Heures')),
                ('created', models.DateTimeField(verbose_name='Date de création')),
                ('updated', models.DateTimeField(verbose_name='Date de modification')),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisie_salarie_list', to='activite.adherent', verbose_name='Adhérent')),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisie_salarie_list', to='releve.relevesalarie', verbose_name='Relevé')),
            ],
        ),
    ]
