# Generated by Django 3.1.3 on 2020-11-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0050_auto_20201105_1653'),
        ('releve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevesalarie',
            name='salarie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releve_heures_list', to='activite.salarie', verbose_name='Salarié'),
        ),
    ]
