# Generated by Django 3.1.3 on 2020-11-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0002_auto_20201119_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevesalarie',
            name='commentaire',
            field=models.TextField(default='', verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='relevesalarie',
            name='saisie_complete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Saisie Complète ?'),
        ),
        migrations.AlterField(
            model_name='relevesalarie',
            name='saisie_complete_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date de Saisie Complete'),
        ),
    ]
