# Generated by Django 3.1.3 on 2020-11-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0003_auto_20201119_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saisiesalarie',
            name='created',
            field=models.DateTimeField(db_index=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='saisiesalarie',
            name='heures',
            field=models.FloatField(db_index=True, default=0, verbose_name='Heures'),
        ),
        migrations.AlterField(
            model_name='saisiesalarie',
            name='updated',
            field=models.DateTimeField(db_index=True, verbose_name='Date de modification'),
        ),
    ]
