# Generated by Django 3.1.3 on 2020-11-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0004_auto_20201120_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='saisiesalarie',
            name='commentaire',
            field=models.TextField(default='', verbose_name='Commentaire'),
        ),
    ]
