# Generated by Django 3.1.3 on 2020-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0006_auto_20201126_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='saisiesalarie',
            name='saved',
            field=models.BooleanField(default=False, verbose_name='Sauvegardé ?'),
        ),
        migrations.AlterField(
            model_name='saisiesalarie',
            name='commentaire',
            field=models.TextField(default='', null=True, verbose_name='Commentaire'),
        ),
    ]
