# Generated by Django 3.1.3 on 2020-11-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0007_auto_20201126_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saisiesalarie',
            name='commentaire',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Commentaire'),
        ),
    ]
