# Generated by Django 3.1.3 on 2020-11-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0008_auto_20201126_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevesalarie',
            name='created',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='relevesalarie',
            name='updated',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='saisiesalarie',
            name='created',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='saisiesalarie',
            name='updated',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Date de modification'),
        ),
    ]
