# Generated by Django 3.1.3 on 2020-12-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0009_auto_20201126_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveSalarieCommentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(db_index=True, default=1, verbose_name='Jour')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('created', models.DateTimeField(db_index=True, editable=False, verbose_name='Date de création')),
                ('updated', models.DateTimeField(db_index=True, editable=False, verbose_name='Date de modification')),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaire_list', to='releve.relevesalarie', verbose_name='Relevé')),
            ],
        ),
    ]
