# Generated by Django 3.1.3 on 2020-12-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0010_relevesalariecommentaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relevesalariecommentaire',
            old_name='commentaire',
            new_name='text',
        ),
    ]
