# Generated by Django 3.1.3 on 2020-12-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0011_auto_20201204_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relevesalarie',
            name='saisie_complete',
        ),
        migrations.RemoveField(
            model_name='relevesalarie',
            name='saisie_complete_date',
        ),
        migrations.AddField(
            model_name='relevesalarie',
            name='gele',
            field=models.BooleanField(db_index=True, default=False, verbose_name='La saisie est gelée ?'),
        ),
    ]
