# Generated by Django 3.1.3 on 2020-12-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0013_auto_20201210_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relevesalarie',
            options={'ordering': ['-annee', '-mois', '-created']},
        ),
    ]
