# Generated by Django 3.1.3 on 2020-12-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0014_auto_20201216_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevesalarie',
            name='total_h',
            field=models.FloatField(db_index=True, default=0, editable=False, verbose_name='Total des heures'),
        ),
    ]
