# Generated by Django 3.1.3 on 2021-02-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releve', '0015_relevesalarie_total_h'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relevesalarie',
            options={'ordering': ['-annee', '-mois', '-created'], 'permissions': [('can_view_ro_releve_salarie', 'Peut voir les relevés des salariés')]},
        ),
    ]
