# Generated by Django 3.2 on 2021-05-26 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conge_valide', models.BooleanField(db_index=True, default=False)),
                ('conge_invalid_motif', models.TextField(blank=True, default='')),
                ('conge_valid_date', models.DateTimeField(db_index=True, null=True)),
                ('debut', models.DateField(db_index=True)),
                ('fin', models.DateField(db_index=True)),
                ('commentaire_salarie', models.TextField(blank=True, default='')),
                ('commentaire_responsable', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('conge_valid_responsable', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_conge_valide_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MotifDemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=30, verbose_name='Libellé')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationAdherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('nom_prenom', models.CharField(max_length=150, verbose_name='Prénom et nom')),
                ('is_valid_manuel', models.BooleanField(blank=True, default=False, verbose_name='Validé manuellement ?')),
                ('valid_manuel_date', models.DateTimeField(db_index=True, null=True, verbose_name='Date de validation manuelle')),
                ('is_valid_timeout', models.BooleanField(blank=True, default=False, verbose_name='Validé par expiration du délais ?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_adherent_list', to='conge.demande')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='motif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_conge_list', to='conge.motifdemandeconge'),
        ),
        migrations.AddField(
            model_name='demande',
            name='salarie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_conge_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
