# Generated by Django 3.2 on 2021-10-20 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0002_rename_demande_demandeconge'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='conge_envoye',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ValidationResponsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid_manuel', models.BooleanField(blank=True, default=False, verbose_name='Validé manuellement ?')),
                ('valid_manuel_date', models.DateTimeField(db_index=True, null=True, verbose_name='Date de validation manuelle')),
                ('is_valid_timeout', models.BooleanField(blank=True, default=False, verbose_name='Validé par expiration du délais ?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_responsable_list', to='conge.demandeconge')),
            ],
        ),
    ]
