# Generated by Django 3.2 on 2021-11-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0004_auto_20211029_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationadherent',
            old_name='id_demande',
            new_name='demande',
        ),
        migrations.AlterField(
            model_name='validationadherent',
            name='slug_acceptation',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Sulg de Validation'),
        ),
        migrations.AlterField(
            model_name='validationadherent',
            name='slug_refus',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Sulg de Validation'),
        ),
        migrations.AlterField(
            model_name='validationadherent',
            name='valid_manuel_date',
            field=models.DateTimeField(db_index=True, default=None, null=True, verbose_name='Date de validation manuelle'),
        ),
    ]
