# Generated by Django 3.2 on 2021-12-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0006_auto_20211224_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validationadherent',
            name='is_valid_manuel',
        ),
        migrations.AddField(
            model_name='validationadherent',
            name='is_valid',
            field=models.BooleanField(blank=True, default=False, verbose_name='Validé ?'),
        ),
        migrations.AlterField(
            model_name='validationadherent',
            name='valid_manuel_date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Date de validation manuelle'),
        ),
    ]
