# Generated by Django 3.2 on 2022-01-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0007_auto_20211229_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationadherent',
            name='refus_manuel_date',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name='Date de validation manuelle'),
        ),
    ]
