# Generated by Django 3.2 on 2022-02-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0008_validationadherent_refus_manuel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='attente_responsable',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
