# Generated by Django 3.2 on 2022-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0009_demandeconge_attente_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationadherent',
            name='is_progressis',
            field=models.BooleanField(blank=True, default=False, verbose_name='Progressis ?'),
        ),
        migrations.DeleteModel(
            name='ValidationResponsable',
        ),
    ]
