# Generated by Django 3.2 on 2022-02-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0010_auto_20220218_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandeconge',
            options={'permissions': [('can_validate_conges', 'Peut valider les congés')]},
        ),
    ]
