# Generated by Django 4.0.3 on 2022-04-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0012_remove_demandeconge_attente_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationadherent',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
    ]
