# Generated by Django 4.0.3 on 2022-04-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0013_alter_validationadherent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationadherent',
            name='is_valid',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Validé ?'),
        ),
    ]
