# Generated by Django 4.0.3 on 2022-04-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0014_alter_validationadherent_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='conge_envoye_date',
            field=models.DateTimeField(db_index=True, default=None, null=True, verbose_name="Date d'envoi du conge paye"),
        ),
    ]
