# Generated by Django 4.0.3 on 2022-05-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0015_demandeconge_conge_envoye_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationadherent',
            name='is_rappel_envoye',
            field=models.BooleanField(blank=True, default=False, verbose_name='Rappel envoyé ?'),
        ),
    ]
