# Generated by Django 4.0.3 on 2022-05-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0016_validationadherent_is_rappel_envoye'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='conge_invalid',
            field=models.BooleanField(default=False),
        ),
    ]
